// <auto-generated />
namespace MoogleGoogle.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class GatheringItemsTimeEndTimeStarttonumeric : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(GatheringItemsTimeEndTimeStarttonumeric));
        
        string IMigrationMetadata.Id
        {
            get { return "201708071442087_GatheringItems TimeEnd, TimeStart to numeric"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
